### ISSUE TITLE
wikipedia link is broken

### ISSUE THREAD

**Issue by abentley** [snapcrafters/mosaic#1]
The link to the Mosaic wikipedia entry lacks the closing parenthesis, so you get Wikipedia saying "	Did you mean: Mosaic (web browser)?"

**Comment by popey** [comment]
Thanks. Worked around via a bodge as `https://en.wikipedia.org/wiki/Mosaic_%28web_browser%29`. Have filed a [bug](https://github.com/canonical-web-and-design/snapcraft.io/issues/2424) against the web rendering component.
